### ISSUE TITLE
Date input in the future

### ISSUE THREAD

**Issue by JKHearMeRoar** [boldMari/AgeCounter#1]
The age calculator does not handle the edge case of inputting future date properly. 

![image](https://github.com/boldMari/AgeCounter/assets/4417829/2a38c089-de1f-41d3-9317-97225bb9db40)

**Comment by boldMari** [comment]
It s fixed in commit c129e5eafb9c29132bdfe2cc99ff6c2ab19b58ca
Thanks for flagging!
